### PR TITLE
Gpu support

### PR DESCRIPTION
**Pull request by SarodYatawatta**
time to merge

### CODE REVIEW

**Comment by fdiblen** [comment]
@SarodYatawatta Did you have a chance to review my changes and try the GPU version?

**Comment by HannoSpreeuw** [comment]
Two comments. 
Yes, I checked everything.
It builds flawlessly.

**Comment by HannoSpreeuw** [comment]
From the `test` directory I tried running `dosage.sh` on the DAS5 headnode, that is a node without a GPU afaik:
`[hspreeuw@fs5 test]$ ./dosage.sh
../src/MS/sagecal: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../src/MS/sagecal)
[hspreeuw@fs5 test]$ vim ~/module.avail`

**Comment by HannoSpreeuw** [comment]
Same error on a node with a GPU after `module load cuda92`.

**Comment by SarodYatawatta** [comment]
Yes, this routine is not needed anymore

**Comment by HannoSpreeuw** [comment]
@fdiblen supplied for two combinations of packages in the script folder.
One for gcc 4.9.3 and one for gcc 6.3.0.

For gcc 4.9.3 everything works.
For gcc 6.3.0. everything builds and the CPU version works.
For the GPU version, however, I get:

> [hspreeuw@node503 test]$ ../src/MS/bin/sagecal_gpu -d sm.ms -s 3c196.sky.txt -c 3c196.sky.txt.cluster  -n 4 -t 10 -p sm.ms.solutions-gpu4 -e 4 -g 2 -l 10 -m 7 -x 30 -F 1 -j 2  -k -1 -B 1 -W 0 > sm.ms.output-gpuv4
../src/MS/bin/sagecal_gpu: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../src/MS/bin/sagecal_gpu)
../src/MS/bin/sagecal_gpu: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ../src/MS/bin/sagecal_gpu)

**Comment by fdiblen** [comment]
> @fdiblen supplied for two combinations of packages in the script folder.
> One for gcc 4.9.3 and one for gcc 6.3.0.
> 
> For gcc 4.9.3 everything works.
> For gcc 6.3.0. everything builds and the CPU version works.
> For the GPU version, however, I get:
> 
> > [hspreeuw@node503 test]$ ../src/MS/bin/sagecal_gpu -d sm.ms -s 3c196.sky.txt -c 3c196.sky.txt.cluster  -n 4 -t 10 -p sm.ms.solutions-gpu4 -e 4 -g 2 -l 10 -m 7 -x 30 -F 1 -j 2  -k -1 -B 1 -W 0 > sm.ms.output-gpuv4
> > ../src/MS/bin/sagecal_gpu: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../src/MS/bin/sagecal_gpu) ../src/MS/bin/sagecal_gpu: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ../src/MS/bin/sagecal_gpu)

@HannoSpreeuw Are you running this in a clean shell environment?

**Comment by HannoSpreeuw** [comment]
Not sure what you mean by "clean shell", but I think the answer is yes.
clean build
`rm -rf *` from within the build directory
`module load cmake/3.8.2
module load gcc/6.3.0
module load casacore/2.4.1-gcc-6.3.0
module load cuda91`

**Comment by HannoSpreeuw** [comment]
Note that I updated my comment. For gcc 6.3.0 also the CPU version does not work.

**Comment by fdiblen** [comment]
> Not sure what you mean by "clean shell", but I think the answer is yes.
> clean build
> `rm -rf *` from within the build directory
> 
> ```
> module load cmake/3.8.2
> module load gcc/6.3.0
> module load casacore/2.4.1-gcc-6.3.0
> module load cuda91
> ```

what do you get when you run **module list**

**Comment by HannoSpreeuw** [comment]
> [hspreeuw@fs5 test]$ module list
Currently Loaded Modulefiles:
  1) slurm/17.02.2              3) cmake/3.8.2                5) wcslib/5.18-gcc-6.3.0      7) casacore/2.4.1-gcc-6.3.0
  2) prun/default               4) gcc/6.3.0                  6) cfitsio/3.430-gcc-6.3.0    8) cuda91/toolkit/9.1.85

**Comment by HannoSpreeuw** [comment]
I agree with @fdiblen that SC should work for later versions of gcc than the very old 4.9.3.
He put forward that a gcc 9.x is now available.
At fs5 the newest gcc is gcc 8.x.
We should have a working SC for gcc 6.3.0 as well. As a bare minimum.

**Comment by HannoSpreeuw** [comment]
Ah, small oversight. `sagecal_gpu` is obviously always run on a node with a GPU.
So my env was not completely the same as on the headnode.
After
`module load gcc/6.3.0`
I get the same invalid pointer error as for the CPU version of SC:

> *** Error in `../src/MS/bin/sagecal_gpu': free(): invalid pointer: 0x0000000000a402b8 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x2aaac3055619]
/cm/shared/package/gcc/6.3.0/lib64/libstdc++.so.6(_ZNSs6assignERKSs+0x8a)[0x2aaac2b10e0a]
/cm/shared/package/casacore/v2.4.1-gcc-6.3.0/lib/libcasa_casa.so.2(_ZN4casa14stringToVectorERKNS_6StringEc+0x130)[0x2aaab0845d90]
/cm/shared/package/casacore/v2.4.1-gcc-6.3.0/lib/libcasa_scimath.so.2(+0x7fc43)[0x2aaaad37dc43]
/lib64/ld-linux-x86-64.so.2(+0xf4c3)[0x2aaaaaaba4c3]
/lib64/ld-linux-x86-64.so.2(+0x11aa)[0x2aaaaaaac1aa]

**Comment by HannoSpreeuw** [comment]
Well, it's actually a `casacore` thing, so I am not sure we can fix this.

**Comment by SarodYatawatta** [comment]
Dont bother if its casacore related

**Comment by fdiblen** [comment]
> Ah, small oversight. `sagecal_gpu` is obviously always run on a node with a GPU.
> So my env was not completely the same as on the headnode.
> After
> `module load gcc/6.3.0`
> I get the same invalid pointer error as for the CPU version of SC:
> 
> > *** Error in `../src/MS/bin/sagecal_gpu': free(): invalid pointer: 0x0000000000a402b8 ***
> > ======= Backtrace: =========
> > /lib64/libc.so.6(+0x7c619)[0x2aaac3055619]
> > /cm/shared/package/gcc/6.3.0/lib64/libstdc++.so.6(_ZNSs6assignERKSs+0x8a)[0x2aaac2b10e0a]
> > /cm/shared/package/casacore/v2.4.1-gcc-6.3.0/lib/libcasa_casa.so.2(_ZN4casa14stringToVectorERKNS_6StringEc+0x130)[0x2aaab0845d90]
> > /cm/shared/package/casacore/v2.4.1-gcc-6.3.0/lib/libcasa_scimath.so.2(+0x7fc43)[0x2aaaad37dc43]
> > /lib64/ld-linux-x86-64.so.2(+0xf4c3)[0x2aaaaaaba4c3]
> > /lib64/ld-linux-x86-64.so.2(+0x11aa)[0x2aaaaaaac1aa]
> 
> We need to debug this.

This is exactly why I was asking about a clean shell environment.

**Comment by HannoSpreeuw** [comment]
All of this emphasizes the need for containers.
I mean, the fact that we can only compile SC with gcc 4.9.3 shows that SC is not easy to install for anyone.
A big part of this is caused by SC's dependencies, like casacore.

**Comment by HannoSpreeuw** [comment]
[This request](https://github.com/nlesc-dirac/sagecal/pull/80#pullrequestreview-203224543) is the only one remaining at this point.

**Comment by SarodYatawatta** [comment]
> All of this emphasizes the need for containers.
> I mean, the fact that we can only compile SC with gcc 4.9.3 shows that SC is not easy to install for anyone.
> A big part of this is caused by SC's dependencies, like casacore.

This is beyond the scope of this pull request, If the GPU version builds, I suggest merging this. I can test if the CPU version builds

**Comment by fdiblen** [comment]
> All of this emphasizes the need for containers.
> I mean, the fact that we can only compile SC with gcc 4.9.3 shows that SC is not easy to install for anyone.
> A big part of this is caused by SC's dependencies, like casacore.

I disagree. Stable CPU version has no issues.

**Comment by SarodYatawatta** [comment]
> From the commit message I cannot infer what is achieved with this new code.
> Please explain.
Ok,
Major change to code: adding stochastic LBFGS code

**Pull request merged**
