### PR TITLE
Containers

### LINKED ISSUE #94: run Sagecal in GPU supported containers
Run Sagecal with GPU support in a container.

For Docker nvidia-docker would be a good starting point.
https://github.com/NVIDIA/nvidia-docker

For Singularity this may help:
https://singularity.lbl.gov/faq#does-singularity-support-containers-that-require-gpus
https://hpc.nih.gov/apps/singularity.html#gpu

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
## Requirements for your pull request
Fixes #94 

Sorry, I branched `containers` off `master` instead of off `dev`. If this is an issue, I will withdraw this PR.

### CODE REVIEW

**Comment by SarodYatawatta** [comment]
It seems there is a conflict, can you resubmit after branching from 'dev'.

**Comment by HannoSpreeuw** [comment]
I tried to rebase but ran into [this problem](https://github.com/nlesc-dirac/sagecal/issues/94#issuecomment-466997472).

**Comment by HannoSpreeuw** [comment]
I referred to #94

**Comment by SarodYatawatta** [comment]
>>src/MPI/sagecal_master.cpp and src/MPI/sagecal_slave.cpp

   >> Why do we have these changes? Any reference/commit id/PR etc?
Because its branched from 'master', not 'dev'
So better use 'dev' to start with

**Pull request closed without merging**
