### PR TITLE
add compile instructions for das5

### PR DESCRIPTION
**Pull request by fdiblen**
added compile instructions for das5.

Could you please check if everything works for you before merging this?

### CODE REVIEW

**Comment by SarodYatawatta** [comment]
Hanno, can you check this and merge?

**Comment by HannoSpreeuw** [comment]
We want to use the latest casacore:
/cm/shared/package/casacore/v2.4.1-gcc-6.3.0

**Comment by fdiblen** [comment]
Let's see if it will work with the new version.

**Comment by fdiblen** [comment]
Btw, are there any major changes between two versions? Why do we prefer the latest?

**Comment by HannoSpreeuw** [comment]
Nothing major, really. It might be more user friendly to use a later casacore.

**Comment by HannoSpreeuw** [comment]
I let it pass. 
Should I delete dev?

**Comment by HannoSpreeuw** [comment]
Sorry, I meant the install_instructions branch.

**Comment by fdiblen** [comment]
Nope, never delete dev!

**Pull request merged**
